#include <iostream>
#include <string>
#include <vector>

using namespace std;

// Leetcode 389: Find the Difference
// You are given two strings s and t. String t is generated by random shuffling string s and then adding one more letter at a random position.
// Return the letter that was added to t.

// MY APPROACH USING TWO FREQUENCY ARRAY

char findTheDifference(string s, string t) {
    vector<int> arr1(26,0);
    vector<int> arr2(26,0);
    int n=s.size();
    for(int i=0; i<n; i++){
        arr1[s[i]-'a']++;
        arr2[t[i]-'a']++;
    }
    arr2[t[n]-'a']++;

    for(int i=0; i<26; i++){
        if(arr1[i]!=arr2[i]){
            return char(i + 'a');
        }
    }
    return 'a'; // unreachable
}


// OPTIMAL APPROACH USING XOR OPERATION
// a ^ a = 0   (Same numbers cancel out)
char findTheDifference(string s, string t) {
    char ans = 0;
    for (char c : s) ans ^= c;
    for (char c : t) ans ^= c;
    return ans;
}



// Using frequency array
char findTheDifference(string s, string t) {
    vector<int> freq(26, 0);

    for (char c : s) freq[c - 'a']--;
    for (char c : t) freq[c - 'a']++;

    for (int i = 0; i < 26; i++)
        if (freq[i] == 1)
            return char(i + 'a');

    return 'a'; // unreachable
}

int main() {
    string s = "abcd";
    string t = "abcde";

    char addedChar = findTheDifference(s, t);
    cout << "The added character is: " << addedChar << endl; // Output: e

    return 0;
}
